GET http://localhost:8080/api/v0/test
Accept: application/json

###

POST http://localhost:8080/api/v0/secure/user
Accept: application/json
Content-Type: application/json
Authorization: Basic YXNzZXNzbWVudDppb25peA==

{
  "name": "Oswaldo Gonzalez",
  "userName": "oagonzalez",
  "email": "no2@mail.com",
  "phone": "3126464260"
}

###
GET http://localhost:8080/api/v0/user/no@mail.com

###
DELETE http://localhost:8080/api/v0/secure/user/no@mail.com
Authorization: Basic YXNzZXNzbWVudDppb25peA==

###
GET http://localhost:8080/api/v0/user

###
GET https://my.api.mockaroo.com/test-tecnico/search/0o2npdu/qB2lVx8uhCHlkQ==

###
POST http://localhost:8080/api/v0/external/search/1-9
Accept: application/json
Content-Type: application/json
